#!/usr/bin/env sh

red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
no_color='\033[0m'

echo -e "\n${yellow}Executing commit-msg hook...${no_color}\n"

npx --no -- commitlint --edit ${1}

echo -e "${green}Git commit-msg hook was successful!${no_color}\n"